"""add isAnonymous column to query

Revision ID: 3d03e41baa31
Revises: 13b36e3e338c
Create Date: 2024-11-25 01:08:36.646298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d03e41baa31'
down_revision: Union[str, None] = '13b36e3e338c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('is_anonymous', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'is_anonymous')
    # ### end Alembic commands ###
